ESX = exports['es_extended']:getSharedObject()

local GetCurrentResourceName = GetCurrentResourceName()
local ox_inventory = exports.ox_inventory

RegisterNetEvent('ox:creativechest', function()
  ox_inventory:RegisterStash('creativechest', Config.NameCreativeMenu, Config.MaxSlots, Config.MaxWeight, true)

  -- Items
  ox_inventory:AddItem('creativechest', 'black_money', 999, {metadata = {}, label = 'Argent Sale', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'bandage', 999, {metadata = {}, label = 'Bandage', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'bmx', 999, {metadata = {}, label = 'BMX', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'wood', 999, {metadata = {}, label = 'Bois', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'cutted_wood', 999, {metadata = {}, label = 'Bois coupé', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'packaged_plank', 999, {metadata = {}, label = 'Bois Emballé', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'gazbottle', 999, {metadata = {}, label = 'Bouteille de Gaz', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'bread', 999, {metadata = {}, label = 'Bread', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'cannabis', 999, {metadata = {}, label = 'Cannabis', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'blowpipe', 999, {metadata = {}, label = 'Chalumeau', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'cola', 999, {metadata = {}, label = 'Coca', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'copper', 999, {metadata = {}, label = 'Cuivre', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'diamond', 999, {metadata = {}, label = 'Diamant', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'water', 999, {metadata = {}, label = 'Eau', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'essence', 999, {metadata = {}, label = 'Essence', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'money', 999, {metadata = {}, label = 'Euro €', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'fabric', 999, {metadata = {}, label = 'Fabric ???', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'iron', 999, {metadata = {}, label = 'Fer', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'scrapmetal', 999, {metadata = {}, label = 'Ferraille', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'armour', 999, {metadata = {}, label = 'GPB', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'identification', 999, {metadata = {}, label = 'Identification', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'carokit', 999, {metadata = {}, label = 'Kit de Carosserie', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'medikit', 999, {metadata = {}, label = 'Kit de Réanimation', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'wool', 999, {metadata = {}, label = 'Laine', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'marijuana', 999, {metadata = {}, label = 'Marijuana', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'mastercard', 999, {metadata = {}, label = 'MasterCard', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'mustard', 999, {metadata = {}, label = 'Moutarde', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'gold', 999, {metadata = {}, label = 'Or', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'carotool', 999, {metadata = {}, label = 'Outils de Carosserie', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'lockpick', 999, {metadata = {}, label = 'Outils de Crochetage', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'fixtool', 999, {metadata = {}, label = 'Outils de Réparation', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'parachute', 999, {metadata = {}, label = 'Parachute', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'petrol', 999, {metadata = {}, label = 'Pétrol', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'petrol_raffin', 999, {metadata = {}, label = 'Pétrol Raffiné', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'stone', 999, {metadata = {}, label = 'Pierre', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'washed_stone', 999, {metadata = {}, label = 'Pierre Lavé', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'fish', 999, {metadata = {}, label = 'Poisson', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'slaughtered_chicken', 999, {metadata = {}, label = 'Poulet Abattus', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'packaged_chicken', 999, {metadata = {}, label = 'Poulet Emballé', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'alive_chicken', 999, {metadata = {}, label = 'Poulet Vivant', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'radio', 999, {metadata = {}, label = 'Radio', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'garbage', 999, {metadata = {}, label = 'Sac Poubelles', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'panties', 999, {metadata = {}, label = 'Snickers', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'phone', 999, {metadata = {}, label = 'Téléphone', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'clothing', 999, {metadata = {}, label = 'Vêtements', slot = 1, stack = true, close = true, weight = 1})
  ox_inventory:AddItem('creativechest', 'clothe', 999, {metadata = {}, label = 'Vêtements', slot = 1, stack = true, close = true, weight = 1})

  -- Example
  -- ox_inventory:AddItem('creativechest', 'bread', 999, {metadata = {}, label = 'Bread', slot = 1, stack = true, close = true, weight = 1})
  Citizen.Wait(30000)

end)

RegisterNetEvent('ox_inventory:stashOpened', function(stashName)
  if stashName == 'creativechest' then
    ox_inventory:AddItem(stashName, 'black_money', 999, {metadata = {}, label = 'Argent Sale', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'bandage', 999, {metadata = {}, label = 'Bandage', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'bmx', 999, {metadata = {}, label = 'BMX', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'wood', 999, {metadata = {}, label = 'Bois', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'cutted_wood', 999, {metadata = {}, label = 'Bois coupé', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'packaged_plank', 999, {metadata = {}, label = 'Bois Emballé', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'gazbottle', 999, {metadata = {}, label = 'Bouteille de Gaz', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'bread', 999, {metadata = {}, label = 'Bread', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'cannabis', 999, {metadata = {}, label = 'Cannabis', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'blowpipe', 999, {metadata = {}, label = 'Chalumeau', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'cola', 999, {metadata = {}, label = 'Coca', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'copper', 999, {metadata = {}, label = 'Cuivre', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'diamond', 999, {metadata = {}, label = 'Diamant', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'water', 999, {metadata = {}, label = 'Eau', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'essence', 999, {metadata = {}, label = 'Essence', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'money', 999, {metadata = {}, label = 'Euro €', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'fabric', 999, {metadata = {}, label = 'Fabric ???', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'iron', 999, {metadata = {}, label = 'Fer', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'scrapmetal', 999, {metadata = {}, label = 'Ferraille', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'armour', 999, {metadata = {}, label = 'GPB', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'identification', 999, {metadata = {}, label = 'Identification', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'carokit', 999, {metadata = {}, label = 'Kit de Carosserie', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'medikit', 999, {metadata = {}, label = 'Kit de Réanimation', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'wool', 999, {metadata = {}, label = 'Laine', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'marijuana', 999, {metadata = {}, label = 'Marijuana', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'mastercard', 999, {metadata = {}, label = 'MasterCard', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'mustard', 999, {metadata = {}, label = 'Moutarde', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'gold', 999, {metadata = {}, label = 'Or', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'carotool', 999, {metadata = {}, label = 'Outils de Carosserie', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'lockpick', 999, {metadata = {}, label = 'Outils de Crochetage', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'fixtool', 999, {metadata = {}, label = 'Outils de Réparation', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'parachute', 999, {metadata = {}, label = 'Parachute', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'petrol', 999, {metadata = {}, label = 'Pétrol', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'petrol_raffin', 999, {metadata = {}, label = 'Pétrol Raffiné', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'stone', 999, {metadata = {}, label = 'Pierre', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'washed_stone', 999, {metadata = {}, label = 'Pierre Lavé', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'fish', 999, {metadata = {}, label = 'Poisson', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'slaughtered_chicken', 999, {metadata = {}, label = 'Poulet Abattus', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'packaged_chicken', 999, {metadata = {}, label = 'Poulet Emballé', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'alive_chicken', 999, {metadata = {}, label = 'Poulet Vivant', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'radio', 999, {metadata = {}, label = 'Radio', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'garbage', 999, {metadata = {}, label = 'Sac Poubelles', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'panties', 999, {metadata = {}, label = 'Snickers', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'phone', 999, {metadata = {}, label = 'Téléphone', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'clothing', 999, {metadata = {}, label = 'Vêtements', slot = 1, stack = true, close = true, weight = 1})
    ox_inventory:AddItem(stashName, 'clothe', 999, {metadata = {}, label = 'Vêtements', slot = 1, stack = true, close = true, weight = 1})

    -- ox_inventory:AddItem(stashName, 'bread', 999, {metadata = {}, label = 'Bread', slot = 1, stack = true, close = true, weight = 1})
    Citizen.Wait(30000)
  end

end)

RegisterCommand("showItems", function()
  local inventory = exports.ox_inventory
  local items = inventory:Items()
  for item, data in pairs(items) do
  print(item, data.label) 
 end
end, false)

RegisterNetEvent('ox:admintrash', function()
  ox_inventory:RegisterStash('admintrash', Config.NameTrashAdmin, Config.MaxSlots, Config.MaxWeightTrash, true)
end)

ESX.RegisterServerCallback('FFDAdmin:getUsergroup', function(source, cb)
  local xPlayer = ESX.GetPlayerFromId(source)
  local group = xPlayer.getGroup()
  cb(group)
end)